### ISSUE TITLE
figure out how to have Travis automatically build this library

### ISSUE THREAD

**Issue by hamilton** [iodide-project/untitled-math-project#1]
iirc, @mdboom has Travis auto-building the Pyodide stack when a new commit hits master. We could easily do this as well, and follow some of his learnings, for this library.

This may be too early on at this point, but figured I'd file an issue anyway.

**Comment by mdboom** [comment]
Yep, should be doable.  For the record, I replaced Travis with Circle-CI, since Travis doesn't give enough time to build pyodide.  But for normal *sane* software, that shouldn't be an issue.  I know Travis a little better, it's been around longer and has a larger community, but I do have to say that I think Circle-CI gets a lot of things much better, especially the ability to ssh into the container when things go wrong...

**Comment by DevinBayly** [comment]
Before I do anything with this I believe I need to get as far as creating a wasm module on npm through the [wasm-pack](https://github.com/rustwasm/wasm-pack) pipeline. When this is done I think it'll be much easier to import the module (for me and others) and tests can get created for whichever tool mentioned above seems most appropriate at that time.

**Comment by rth** [comment]
Could someone please enable Circle CI on this repo?

I could make a PR with a basic CI setup -- I agree Circle CI would be best, as it would allow to directly use a Docker image with the Rust nightly without having to install it.

> Before I do anything with this I believe I need to get as far as creating a wasm module on npm through the wasm-pack pipeline.

Are you sure that is needed? I mean one could add a CI that would at least build this (runs some of the rust tests I saw) even if it's not on npm?

**Comment by mdboom** [comment]
I'll turn it on Circle-CI so we can experiment.

**Comment by DevinBayly** [comment]
Disclaimer, I haven't interacted with Circle CI at all (excited for this to change), but if its something that the owner of the repo needs to do I can look up some instructions for this.

With regards to the npm wasm module, this now exists, and I would love to see what you have in mind for the CI rust testing.

**Comment by DevinBayly** [comment]
@mdboom swooped in for the kill! Anways, the second thing I said still goes.

**Comment by mdboom** [comment]
@rth: I think you should now be able to file a PR with a `.circleci/config.yaml` and start testing.

**Comment by rth** [comment]
Great, thanks!

**Comment by DevinBayly** [comment]
Thanks for handling it @mdboom .

**Comment by rth** [comment]
Hmm, Circle CI did trigger on master, but for some reason, not on PR  https://github.com/iodide-project/untitled-math-project/pull/3 

@mdboom Maybe build of PRs from forks was not enabled in the Circle CI UI?

**Comment by rth** [comment]
@mdboom could you please enable CI builds for forks, under
"Circle CI Project Settings -> Advanced Settings -> Build forked pull requests -> On".

As in the current state, CI is not very useful.. Thanks!

**Comment by mdboom** [comment]
Done.
