### ISSUE TITLE
[META] add benchmarks

### ISSUE THREAD

**Issue by hamilton** [iodide-project/untitled-math-project#2]
<img width="907" alt="screen shot 2018-07-12 at 3 14 44 pm" src="https://user-images.githubusercontent.com/95735/42662454-8296338a-85e6-11e8-9a2d-a2e3d0072d41.png">
The Julia folk have this well-known graph showing how Julia compares to other stacks for a handful of benchmarks. We chatted a bit about this during the Iodide project meeting, but to make it explicit - it'd be great to make an updated, interactive version of the same chart w/ those benchmarks for this lib / pyodide calls.  I think it'd be a useful signal to the world that demonstrates we are taking performance considerations seriously.

**Comment by DevinBayly** [comment]
naively tracking benchmarks is going to look like adding compatible methods to the api such that the scijs/ndarray benchmarking process ([see experiment dir here](https://github.com/mikolalysenko/ndarray-experiments)) can work on the wasm ndarray module.

I still haven't cracked the case of how to cleverly track how these results change over time, but I'm confident that when more functionality is included, we can start extending the benchmark described above to report back results on matrix mult, parsing ints, and other trials in julia's graph
